version: '3.8'

services:
  caddy:
    image: caddy/caddy:2.7.6-alpine
    container_name: caddy
    restart: unless-stopped
    environment:
      - CF_API_TOKEN=ux47kvk7UmbOIumdqA4cqgPeOZPLvSBGteYhQo8J
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - rust_app_network

volumes:
  caddy_data:
  caddy_config:
